---
output: github_document
---

<!--
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

```{r load_libraries, include=FALSE}
source("https://github.com/kctolli/kctolli.github.io/raw/master/site_libs/script.R")
datapath <- "https://github.com/kctolli/kctolli.github.io/raw/master/site_libs/data/"
load_libraries()
```

# Kyle Tolliver

* [Portfolio](https://kctolli.github.io/)
  + [Resume](https://kctolli.github.io/site_libs/resume/resume.html)
  + [Diploma](https://kctolli.github.io/site_libs/images/diploma.pdf)

## User Stats

`r user_stats()`

## Highlights

```{r highlights}
highlights <- read_csv(glue("{datapath}highlights.csv"))
glue_data(highlights, "- [{Text}]({Link}) \n")
```

`r pagebreak()`

`r copyright()`